#!/bin/sh
#
# An example hook script to blocks unannotated tags from entering.
# Called by git-receive-pack with arguments: refname sha1-old sha1-new
#
# To enable this hook, rename this file to "update".
#
# Config
# ------
# hooks.allowunannotated
#   This boolean sets whether unannotated tags will be allowed into the
#   repository.  By default they won't be.
# hooks.allowdeletetag
#   This boolean sets whether deleting tags will be allowed in the
#   repository.  By default they won't be.
# hooks.allowmodifytag
#   This boolean sets whether a tag may be modified after creation. By default
#   it won't be.
# hooks.allowdeletebranch
#   This boolean sets whether deleting branches will be allowed in the
#   repository.  By default they won't be.
# hooks.denycreatebranch
#   This boolean sets whether remotely creating branches will be denied
#   in the repository.  By default this is allowed.
#

# --- Command line
refname="$1"
oldrev="$2"
newrev="$3"

if [ -f /tmp/git_branch_nu ]; then
	branch_nu=`cat /tmp/git_branch_nu`
#	echo $branch_nu
else
	branch_nu=0;
fi

if [ "$branch_nu" != "0" ]; then
	echo "Sorry, you can't push multiple branches!"
	echo 0 > /tmp/git_branch_nu
	exit 1
fi

branch_nu=$((branch + 1))
echo "$branch_nu" > /tmp/git_branch_nu

exit 0
